### ISSUE TITLE
Don't work run the current file in version 11.5_alpha

### ISSUE THREAD

**Issue by 9Demien9** [orbitalquark/textadept#277] opened 2022-10-12 06:16 UTC
Hello!
In version 11.5_alpha don't work run the current file.
It does not work either through the menu or via ctrl+r.
Output the string: Run command: lua -e "io.stdout:setvbuf('no')" "%f"
In version 11.4 all work.

System: Debian 11

**Comment by orbitalquark** [comment] 2022-10-12 12:21
Textadept 11.5 alpha now uses the command entry to run commands, so initially you will get that prompt. Press Enter to confirm that is the command that you want to run, and it should do so.

**Comment by 9Demien9** [comment] 2022-10-13 05:12
> Textadept 11.5 alpha now uses the command entry to run commands, so initially you will get that prompt. Press Enter to confirm that is the command that you want to run, and it should do so.

No, nothing happens after pressing Enter.

**Comment by orbitalquark** [comment] 2022-10-13 12:45
Okay, then I don't know what the problem is. With a fresh install of Textadept 11.5 alpha on Linux (running with -u /tmp), I am able to run Lua files without issue after confirming with Enter. Lua is installed on your machine, right?

**Comment by 9Demien9** [comment] 2022-10-13 12:50
> Okay, then I don't know what the problem is. With a fresh install of Textadept 11.5 alpha on Linux (running with -u /tmp), I am able to run Lua files without issue after confirming with Enter. Lua is installed on your machine, right?

Of course, Lua is installed. Version 11.4 is quite enough for me. I  found this behavior in 11.5, and decided to specify

**Comment by orbitalquark** [comment] 2024-09-16 00:48
This has not been reported by anyone else, so closing.

**Closed as completed by orbitalquark** 2024-09-16 00:48 UTC
